services:
  - type: web
    name: ai-chatbot-sugarcane
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: python -m flask run --host=0.0.0.0 --port $PORT --no-reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
    healthCheckPath: /
    autoDeploy: true
